In [1]:
import pandas as pd

In [2]:
test_df = pd.read_csv('predictions.csv')

In [3]:
test_df

           ImageId                                   PredictionString
0     ID_18fb86d04                                                NaN
1     ID_ce06d4dc1                                                NaN
2     ID_afe07078f  0.18453103 -0.0006970451895857946 -3.099381128...
3     ID_37caf75aa                                                NaN
4     ID_7655363ca                                                NaN
...            ...                                                ...
2016  ID_a36374d4f                                                NaN
2017  ID_998f76276  0.18276699 0.06892893386023066 -3.114174610125...
2018  ID_427dfeea1  0.19050267 0.009726149709584249 -3.10467992176...
2019  ID_94b297779                                                NaN
2020  ID_53514d85d                                                NaN

[2021 rows x 2 columns]

In [11]:

test_df = pd.read_csv('resnet1.39_test_predictions.csv')

In [12]:
test_df

           ImageId                                   PredictionString
0     ID_18fb86d04                                                NaN
1     ID_ce06d4dc1  0.15168878 0.03136103240310034 -3.093124164389...
2     ID_afe07078f  0.14725205 -3.1175437021330072 -3.114775860803...
3     ID_37caf75aa  0.14440101 0.029690349729182115 -3.09231269930...
4     ID_7655363ca  0.14945076 -3.1020737579883715 -3.124565327661...
...            ...                                                ...
2016  ID_a36374d4f  0.13975449 0.014615686605235946 -3.09135394369...
2017  ID_998f76276  0.14408834 -3.1170658245383733 -3.116672260808...
2018  ID_427dfeea1  0.14929865 -0.021595988744436852 -3.0998504554...
2019  ID_94b297779  0.15264648 -0.017911865747673325 -3.1034276468...
2020  ID_53514d85d  0.16225187 0.029275745541637862 -3.10259096150...

[2021 rows x 2 columns]